ktor:
  deployment:
    port: 8080
  application:
    modules:
      - backend.ApplicationKt.module

security:
  jwt:
    issuer: "agora.auth"
    audience: "agora.clients"
    realm: "Access to Agora API"
    secret: "super_secret_dev_key_change_me"
    expiresInMinutes: 60

db:
  # --- ¡CAMBIO AQUÍ! ---
  # Apunta a tu IP Elástica de AWS en lugar de 'localhost'
  url: "jdbc:postgresql://34.192.122.244:5432/agora_db"

  # (Este es el usuario 'postgres' de tu instancia EC2)
  user: "postgres"

  # (Esta es la contraseña 'jeselmorzu08' que pusiste en el script)
  password: "jeselmorzu08"

cloudinary:
  cloud_name: "dsvsmbw86"
  api_key: "822122624443347"
  api_secret: "MFuwVULnO0_O7HgyTzRXpcJy5S8"